import Head from 'next/head'

export default function Layout ({children}){
    return(
        <>
        <Head>
        <title>Youtube Downloader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.1.2/tailwind.min.css" integrity="sha512-RntatPOhEcQEA81gC/esYoCkGkL7AYV7TeTPoU+R9zE44/yWxVvLIBfBSaMu78rhoDd73ZeRHXRJN5+aPEK53Q==" crossorigin="anonymous" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        {children}
        </main>
    </>
    )
}

